### ISSUE TITLE
The "Nested Hashes Model Real-World Data" section is a little inaccurate.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/nested-hashes-intro#3]
Hello! The "Nested Hashes Model Real-World Data" section mentions that "there is no way to associate our two arrays and tell them that they both belong to the Flatiron School." The arrays that it mentions are:

instructors = ["Avi", "Jeff", "Rose"] and dev_team = ["Jonas", "Logan", "Amanda", "Seiji", "Kate", "Spencer"]

However, there IS an alternative way, besides using nested hashes, to associate the two arrays and show that they both belong to Flatiron School: by using a nested array.

If you make a nested array called flatiron_school = [ ["instructors", instructors], ["dev_team", dev_team] ], then this is what gets created:

[ ["instructors", ["Avi", "Jeff", "Rose"] ], ["dev_team", ["Jonas", "Logan", "Amanda", "Seiji", "Kate", "Spencer"] ] ]

Admittedly, this is not nearly as accessible or easy-to-read as a nested hash, but it is an alternative that I think is worth mentioning.

Thanks for looking into this!

Sdcrouse

**Comment by sgharms** [comment]
Thanks for the suggestion.
